### ISSUE TITLE
Title page decorations (logo, social links, buttons)

### ISSUE THREAD

**Issue by mslw** [datalad/distribits-2024-website#2]
The landing page can look [like this](https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode), i.e. have in the center not just title & subtitle, but also logo, social buttons (mastodon etc.), and some text buttons. Pieces are controlled via `config.toml`.

I was thinking if and what we need to add, and found no must-haves (without these decorations looks good too), but I'm leaving a note that this is possible.

**Comment by jsheunis** [comment]
Added in 85c729b
